//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBrowser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class eBrowserResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal eBrowserResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eBrowser.eBrowserResource", typeof(eBrowserResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon e621Icon {
            get {
                object obj = ResourceManager.GetObject("e621Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body&gt;
        ///&lt;style&gt;
        ///	body 
        ///	{
        ///		background-color: #152F56;
        ///	}
        ///
        ///	.cover {
        ///	  object-fit: contain;
        ///	  width: 100%;
        ///	  height: 100%;
        ///	}
        ///&lt;/style&gt;
        ///&lt;img id=&quot;main-img&quot; class=&quot;cover&quot; src=&quot;{IMAGE_URL}&quot;/&gt;
        ///&lt;/body&gt;.
        /// </summary>
        internal static string ImageViewHTML {
            get {
                return ResourceManager.GetString("ImageViewHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body&gt;
        ///&lt;style&gt;
        /// body { background-color: #152F56; }
        /// .cover { object-fit: contain; width: 100%; height: 100%; }
        ///&lt;/style&gt;
        ///&lt;video id=&quot;vid&quot; class=&quot;cover&quot; controls loop{ADDITIONAL_PARAM}&gt; &lt;source id=&quot;video-source&quot; src=&quot;{VIDEO_URL}&quot;&gt; Your browser does not support the video tag. &lt;/video&gt; 
        ///&lt;script&gt; function playVideo() { document.getElementById(&quot;vid&quot;).play(); } function pauseVideo() { document.getElementById(&quot;vid&quot;).pause(); } &lt;/script&gt;
        ///&lt;/body&gt;.
        /// </summary>
        internal static string VideoViewHTML {
            get {
                return ResourceManager.GetString("VideoViewHTML", resourceCulture);
            }
        }
    }
}
